# Generated by Django 6.0.3 on 2026-03-19 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('element', models.CharField(choices=[('fuego', 'Fuego'), ('agua', 'Agua'), ('tierra', 'Tierra'), ('rayo', 'Rayo'), ('sombra', 'Sombra'), ('cristal', 'Cristal'), ('viento', 'Viento'), ('hielo', 'Hielo')], max_length=20, verbose_name='Categoría elemental')),
                ('threat_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nivel de amenaza')),
                ('description', models.TextField(verbose_name='Descripción de campo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Criatura',
                'verbose_name_plural': 'Criaturas',
                'ordering': ['name'],
            },
        ),
    ]
