# Generated by Django 6.0.3 on 2026-03-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_creature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveSmallIntegerField(verbose_name='HP')),
                ('attack', models.PositiveSmallIntegerField(verbose_name='Ataque')),
                ('defense', models.PositiveSmallIntegerField(verbose_name='Defensa')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='Velocidad')),
                ('creature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_stats', to='catalog.creature')),
            ],
            options={
                'verbose_name': 'Estadísticas de combate',
            },
        ),
    ]
